### ISSUE TITLE
Finalize Milestone 1 Report Template

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#40]
For the Milestone 1 Report template:

- [ ] Review my changes to the "Potential Directions for Design Research" slide
- [ ] Delete the old slide with the big red box
- [ ] Promote the deck from "Ready to Review" up to the main folder
  - Make a mental note to put templates in such a folder when they are pending my review
- [ ] The folder is now empty and should be deleted

Optional:
- 🍨 for all the Milestone 1 templates being complete

**Comment by JesseDoesHCI** [comment]
✅ 🍨 🥳
