### ISSUE TITLE
Create and Finalize Rubric for Milestone 1 Report

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#41]
Promoting this from within #27.

- [x] Jesse to draft rubric in website.
- [x] James to review and publish.
- [x] Jesse to apply within Canvas.
- [x] Jesse to publish Canvas assignment.

**Comment by JesseDoesHCI** [comment]
- [x] Jesse to apply within Canvas
- [x] Jesse to publish Canvas assignment
