### ISSUE TITLE
Review Milestone Overviews

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#43]
I have added and published milestone overviews in #42.

For convenience, I also gathered them in a document:

https://docs.google.com/document/d/1AIZeEjsitrC2HOF_uQUWY0ne5o5TZ4Cutr4lQpDYs44/edit

- [ ] Review the milestone overview text.
- [ ] If it all looks good, delete that document and close this issue.
- [ ] If there is something to change or improve, flag it to me in the Google Doc.

**Comment by JesseDoesHCI** [comment]
looks great!
